// <auto-generated />
using System;
using FocusTrack.RewardWorker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FocusTrack.RewardWorker.Migrations
{
    [DbContext(typeof(RewardsDbContext))]
    partial class RewardsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FocusTrack.RewardWorker.Persistence.DailyFocusContribution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("CalendarDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DurationMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CalendarDate", "SessionId")
                        .IsUnique();

                    b.ToTable("DailyFocusContributions");
                });

            modelBuilder.Entity("FocusTrack.RewardWorker.Persistence.DailyGoalAchievement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("CalendarDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TriggeringSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CalendarDate")
                        .IsUnique();

                    b.ToTable("DailyGoalAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
